/*
 * This source file was generated by the Gradle 'init' task
 */
package DI.app.src.test.java.di;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
